project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
preserve_hierarchy: false

files:
  - source: /i18n/locales/en.json
    translation: /i18n/locales/%two_letters_code%.json
