#!/usr/bin/env bash
set -euo pipefail

# â”€â”€â”€ setup.sh â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
# One-time setup: generates a .env file with random secrets.
# Run once, then: docker compose up
# â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

if [ -f .env ]; then
  echo ""
  echo "âš ï¸  .env already exists."
  echo "   Delete it first if you want to regenerate secrets:"
  echo "   rm .env && ./setup.sh"
  echo ""
  exit 1
fi

if ! command -v openssl &> /dev/null; then
  echo "âŒ  openssl is required but not found. Install it and try again."
  exit 1
fi

AUTH_SECRET=$(openssl rand -base64 32)
DB_PASS=$(openssl rand -hex 16)
STORAGE_PASS=$(openssl rand -hex 16)

cat > .env <<EOF
# â”€â”€â”€ WWMate â€” generated by setup.sh â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# â— Do NOT commit this file. See .env.example for production variable reference.

# â”€â”€â”€ Database â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
DB_USER=WWMate
DB_PASSWORD=${DB_PASS}
DB_NAME=WWMate

# Used by host tools (drizzle-kit, drizzle studio). docker-compose overrides
# this with the internal Docker hostname for the app container.
DATABASE_URL=postgresql://WWMate:${DB_PASS}@localhost:5432/WWMate

# â”€â”€â”€ Authentication â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
BETTER_AUTH_SECRET=${AUTH_SECRET}
BETTER_AUTH_URL=http://localhost:3000

# â”€â”€â”€ Object Storage â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
STORAGE_USER=WWMate
STORAGE_PASSWORD=${STORAGE_PASS}

# Used by host tools. docker-compose overrides this for the app container.
S3_ENDPOINT=http://localhost:9000
S3_ACCESS_KEY=WWMate
S3_SECRET_KEY=${STORAGE_PASS}
S3_BUCKET=WWMate
S3_REGION=us-east-1
S3_FORCE_PATH_STYLE=true

# â”€â”€â”€ SEO â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
NUXT_PUBLIC_SITE_URL=http://localhost:3000
EOF

echo ""
echo "âœ…  .env generated with random secrets."
echo ""
echo "Start the stack:"
echo "  docker compose up"
echo ""
echo "App â†’ http://localhost:3000"
echo ""
echo "Optional â€” seed demo account (after the app is running):"
echo "  docker compose exec app npm run db:seed"
echo "  Login: demo@WWMate.com / demo1234"
echo ""

