name: Bug report
description: Report a reproducible defect in Reqcore
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please provide enough detail for us to reproduce quickly.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Exact steps, in order.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: What happened instead?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version / commit
      description: Branch, tag, or commit SHA where you observed the issue.
      placeholder: main @ abc123

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, browser, Docker version, Node version, and any relevant setup details.
      placeholder: Linux, Chrome 123, Docker 27, Node 20

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant logs, stack traces, or screenshots.
      render: shell
