name: Feature request
description: Propose an improvement to Reqcore
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing a feature. Focus on user value and concrete outcomes.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What pain point are you trying to solve?
      placeholder: As a recruiter, I struggle with ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What should Reqcore do?
      placeholder: Add a ... page / API / workflow that ...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workaround or other options you've considered.

  - type: textarea
    id: scope
    attributes:
      label: Scope and impact
      description: Who benefits, and how should success be measured?
      placeholder: This helps hiring teams by ...

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and did not find a duplicate.
          required: true
        - label: This request aligns with Reqcore's ownership/transparency/privacy direction.
          required: false
