import { z } from "zod";
import { resolveDatabaseUrl } from "./database-url";

/**
 * Preprocessor that normalizes empty strings to undefined.
 * Railway and some platforms may set env vars to "" instead of leaving them unset.
 * This ensures `.default()` and `.optional()` work as expected.
 */
const emptyToUndefined = z.preprocess(
  (val) => (typeof val === "string" && val.trim() === "" ? undefined : val),
  z.string(),
);

/**
 * Detect whether the current Railway environment is a PR/preview environment.
 * Production and long-lived environments must provide explicit BETTER_AUTH_URL.
 */
export function isRailwayPreviewEnvironment(environmentName?: string): boolean {
  const name = environmentName?.toLowerCase().trim() ?? "";

  if (!name) return false;

  // Never treat production as preview.
  if (name === "production" || name === "prod") return false;

  return (
    name.startsWith("pr") ||
    /^pr(?:-|\d)/.test(name) ||
    name.includes("pr-") ||
    name.includes("pr ") ||
    name.includes("pull request") ||
    name.includes("pull-request") ||
    name.includes("preview")
  );
}

/** @internal Exported for unit testing. */
export const envSchema = z
  .object({
    DATABASE_URL: z.url(),
    BETTER_AUTH_SECRET: emptyToUndefined.pipe(
      z.string().min(32, "BETTER_AUTH_SECRET must be at least 32 characters"),
    ),
    BETTER_AUTH_URL: z
      .preprocess((val) => {
        if (typeof val !== "string") return val;
        const trimmed = val.trim();
        // Treat empty strings and broken Railway template refs ("https://") as unset
        if (trimmed === "" || trimmed === "https://" || trimmed === "http://")
          return undefined;
        return trimmed;
      }, z.string().url())
      .optional(),
    /** Comma-separated list of additional trusted origins for Better Auth CSRF checks. */
    BETTER_AUTH_TRUSTED_ORIGINS: emptyToUndefined
      .pipe(z.string())
      .transform((value) =>
        value
          .split(",")
          .map((origin) => origin.trim())
          .filter(Boolean),
      )
      .optional()
      .default([]),
    /** Railway environment metadata for PR/preview detection. */
    RAILWAY_ENVIRONMENT_NAME: emptyToUndefined.optional(),
    /** PR number provided by Railway for GitHub-triggered deployments. */
    RAILWAY_GIT_PR_NUMBER: emptyToUndefined
      .pipe(z.string().regex(/^\d+$/, "RAILWAY_GIT_PR_NUMBER must be numeric"))
      .optional(),
    /** Public domain generated by Railway for the current deployment. */
    RAILWAY_PUBLIC_DOMAIN: emptyToUndefined.optional(),
    S3_ENDPOINT: z.url(),
    S3_ACCESS_KEY: emptyToUndefined.pipe(z.string().min(1)),
    S3_SECRET_KEY: emptyToUndefined.pipe(z.string().min(1)),
    S3_BUCKET: emptyToUndefined.pipe(z.string().min(1)),
    S3_REGION: emptyToUndefined
      .pipe(z.string().min(1))
      .optional()
      .default("us-east-1"),
    /** Use path-style S3 URLs. Required for MinIO (local dev), must be `false` for Railway Buckets / AWS S3. */
    S3_FORCE_PATH_STYLE: z.preprocess(
      (val) =>
        typeof val === "string" && val.trim() === ""
          ? undefined
          : val === "true" || val === undefined,
      z.boolean().default(true),
    ),
    /**
     * How far forwarding headers are trusted when resolving the client IP for
     * rate limiting: `cloudflare` (read CF-Connecting-IP), a hop count 1-10
     * (Nth X-Forwarded-For entry from the right), or `none` (socket peer only).
     * Defaults to `cloudflare` in production — set `none` when the app is
     * exposed directly to the internet.
     */
    TRUSTED_PROXY: emptyToUndefined.optional(),
    /** Legacy: IP address of the trusted reverse proxy. When set, X-Forwarded-For is trusted only for requests whose socket peer matches it. Superseded by TRUSTED_PROXY. */
    TRUSTED_PROXY_IP: z.string().min(1).optional(),
    /** Slug of the demo organization. When set, write operations are blocked for this org. */
    DEMO_ORG_SLUG: emptyToUndefined.optional(),
    /** Fine-grained GitHub PAT with Issues:write scope. When set (along with GITHUB_FEEDBACK_REPO), enables in-app feedback. */
    GITHUB_FEEDBACK_TOKEN: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** GitHub repo in "owner/repo" format for feedback issues. */
    GITHUB_FEEDBACK_REPO: emptyToUndefined
      .pipe(
        z.string().regex(/^[^/]+\/[^/]+$/, 'Must be in "owner/repo" format'),
      )
      .optional(),
    /** Resend API key for transactional emails (invitations, etc.). When not set, emails are logged to console. */
    RESEND_API_KEY: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Full-access Resend API key used only to retrieve inbound candidate emails. */
    RESEND_RECEIVING_API_KEY: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Sender email address for Resend emails. Must be a verified domain in Resend. Defaults to "Reqcore <noreply@reqcore.com>". */
    RESEND_FROM_EMAIL: emptyToUndefined
      .pipe(z.string().min(1))
      .optional()
      .default("Reqcore <noreply@reqcore.com>"),
    /** Reply-friendly sender identity used only for candidate conversations. */
    RESEND_CANDIDATE_FROM_EMAIL: emptyToUndefined
      .pipe(z.string().min(1))
      .optional()
      .default("Reqcore Messages <messages@reqcore.com>"),
    /** Dedicated inbound subdomain used for per-conversation Reply-To addresses. */
    RESEND_REPLY_DOMAIN: emptyToUndefined
      .pipe(z.string().regex(/^(?!https?:\/\/)[a-z0-9.-]+$/i, 'Must be a domain name without a protocol'))
      .optional(),
    /** Signing secret for the Resend webhook that handles inbound mail and delivery events. */
    RESEND_WEBHOOK_SECRET: emptyToUndefined.pipe(z.string().min(16)).optional(),
    /** SMTP hostname for outbound email (e.g. smtp.gmail.com). When set, SMTP is used instead of Resend. */
    SMTP_HOST: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** SMTP port. Defaults to 587 (STARTTLS). Use 465 for implicit TLS, 25 for unencrypted. */
    SMTP_PORT: z.preprocess(
      (val) => {
        if (typeof val === 'string' && val.trim() === '') return 587
        if (val === undefined) return 587
        const n = Number(val)
        return Number.isNaN(n) ? val : n
      },
      z.number().int().min(1).max(65535).default(587),
    ),
    /** SMTP username for authentication. Omit for anonymous relay. */
    SMTP_USER: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** SMTP password for authentication. Omit for anonymous relay. */
    SMTP_PASS: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Sender address for SMTP emails. Defaults to "Reqcore <noreply@reqcore.com>". */
    SMTP_FROM: emptyToUndefined
      .pipe(z.string().min(1))
      .optional()
      .default('Reqcore <noreply@reqcore.com>'),
    /** Use implicit TLS on port 465. When false, uses STARTTLS (port 587). Defaults to false. */
    SMTP_SECURE: z.preprocess(
      (val) => typeof val === 'string' && val.trim() === '' ? false : val === 'true',
      z.boolean().default(false),
    ),
    /** Google OAuth2 Client ID for Calendar integration. Obtain from Google Cloud Console. */
    GOOGLE_CLIENT_ID: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Google OAuth2 Client Secret for Calendar integration. */
    GOOGLE_CLIENT_SECRET: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Google OAuth2 Client ID for social sign-in. Obtain from Google Cloud Console → Credentials. */
    AUTH_GOOGLE_CLIENT_ID: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Google OAuth2 Client Secret for social sign-in. */
    AUTH_GOOGLE_CLIENT_SECRET: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** GitHub OAuth App Client ID for social sign-in. Obtain from GitHub Developer Settings. */
    AUTH_GITHUB_CLIENT_ID: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** GitHub OAuth App Client Secret for social sign-in. */
    AUTH_GITHUB_CLIENT_SECRET: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Microsoft Entra ID Client ID for social sign-in. Obtain from Azure Portal → App Registrations. */
    AUTH_MICROSOFT_CLIENT_ID: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Microsoft Entra ID Client Secret for social sign-in. */
    AUTH_MICROSOFT_CLIENT_SECRET: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Microsoft Entra ID Tenant ID. Defaults to 'common' (multi-tenant). */
    AUTH_MICROSOFT_TENANT_ID: emptyToUndefined.pipe(z.string().min(1)).optional().default('common'),
    /** Shared secret for authenticating cron/scheduled job requests (e.g., webhook renewal). */
    CRON_SECRET: emptyToUndefined.pipe(z.string().min(16)).optional(),
    /**
     * Instance-wide master switch for automated GDPR retention processing.
     * Fail-closed: defaults to OFF so an irreversible erasure sweep never runs
     * unless an operator explicitly opts in with GDPR_CLEANUP_ENABLED=true.
     * Organization-level `retentionEnabled` is a second, independent guard — both
     * must be on for any candidate to be quarantined or erased. Setting this to
     * false also serves as the instance-wide emergency pause.
     */
    GDPR_CLEANUP_ENABLED: z.preprocess(
      val => val === undefined || val === '' ? false : val === true || val === 'true',
      z.boolean().default(false),
    ),
    /**
     * Kill-switch for the recruiter notification engine. Fail-safe default = ON:
     * notifications are an activation driver and are safe to send. Set to false to
     * pause all outbox draining/digests instance-wide (checked at the top of the
     * dispatch + digest workers). Mirrors the GDPR_CLEANUP_ENABLED idiom.
     */
    NOTIFICATIONS_ENABLED: z.preprocess(
      val => val === undefined || val === '' ? true : val === true || val === 'true',
      z.boolean().default(true),
    ),
    // ── Platform AI gateway (optional) ──────────────────────────
    // When OPENROUTER_API_KEY is set, orgs without their own AI config fall back
    // to our platform key, routed through OpenRouter for unified billing and
    // analytics. Platform-paid runs are subject to the budget gate (utils/ai/
    // budget.ts); BYOK orgs are unaffected. Leave unset to keep BYOK-only.
    /** OpenRouter API key (sk-or-…). Enables platform-paid AI for orgs without their own key. */
    OPENROUTER_API_KEY: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Default model for platform-paid runs, OpenRouter-prefixed. Defaults to google/gemini-3.5-flash-lite. */
    OPENROUTER_MODEL: emptyToUndefined.pipe(z.string().min(1)).optional().default('google/gemini-3.5-flash-lite'),
    /** Global platform-wide daily AI spend cap in USD (runaway-loop kill-switch). Defaults to 25. */
    AI_DAILY_SPEND_CAP_USD: emptyToUndefined
      .pipe(z.string().regex(/^\d+(\.\d+)?$/, 'Must be a number'))
      .optional(),
    /** OIDC client ID for SSO authentication (e.g., Keycloak, Authentik, Authelia, Okta). */
    OIDC_CLIENT_ID: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** OIDC client secret for SSO authentication. */
    OIDC_CLIENT_SECRET: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** OIDC discovery URL (must point to a .well-known/openid-configuration endpoint). */
    OIDC_DISCOVERY_URL: emptyToUndefined.pipe(
      z.string().url().refine(
        (url) => url.startsWith('https://') || url.startsWith('http://'),
        'OIDC_DISCOVERY_URL must use HTTPS (or HTTP for local development)',
      ),
    ).optional(),
    /** Display name for the SSO button (e.g., "Company SSO", "Keycloak"). Defaults to "SSO". */
    OIDC_PROVIDER_NAME: emptyToUndefined
      .pipe(z.string().min(1))
      .optional()
      .default("SSO"),

    // ── Stripe Billing (optional) ───────────────────────────
    // When STRIPE_SECRET_KEY is set, self-serve subscription checkout is enabled.
    // All Stripe vars are all-or-none (enforced in superRefine below): leaving
    // STRIPE_SECRET_KEY unset disables billing entirely (self-hosters unaffected).
    /** Stripe secret API key (sk_test_… / sk_live_…). Enables the billing feature when set. */
    STRIPE_SECRET_KEY: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Stripe webhook signing secret (whsec_…). Verifies authenticity of webhook events. */
    STRIPE_WEBHOOK_SECRET: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Stripe recurring price id for Solo, monthly billing. */
    STRIPE_PRICE_SOLO_MONTHLY: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Stripe recurring price id for Solo, annual billing. */
    STRIPE_PRICE_SOLO_ANNUAL: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Stripe recurring price id for Team, monthly billing. */
    STRIPE_PRICE_TEAM_MONTHLY: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Stripe recurring price id for Team, annual billing. */
    STRIPE_PRICE_TEAM_ANNUAL: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Stripe recurring price id for Scale, monthly billing. */
    STRIPE_PRICE_SCALE_MONTHLY: emptyToUndefined.pipe(z.string().min(1)).optional(),
    /** Stripe recurring price id for Scale, annual billing. */
    STRIPE_PRICE_SCALE_ANNUAL: emptyToUndefined.pipe(z.string().min(1)).optional(),
  })
  .superRefine((data, ctx) => {
    // BETTER_AUTH_URL can be derived at runtime from RAILWAY_PUBLIC_DOMAIN,
    // so it's only required when not running on Railway.
    if (!data.BETTER_AUTH_URL && !data.RAILWAY_PUBLIC_DOMAIN) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["BETTER_AUTH_URL"],
        message:
          "BETTER_AUTH_URL is required when RAILWAY_PUBLIC_DOMAIN is not available",
      });
    }

    // SMTP: credentials without a host is a misconfiguration.
    if (!data.SMTP_HOST && (data.SMTP_USER || data.SMTP_PASS)) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['SMTP_HOST'],
        message: 'SMTP_HOST is required when SMTP_USER or SMTP_PASS is set.',
      })
    }

    // OIDC SSO requires all three vars or none — partial config is a misconfiguration.
    const oidcVars = [
      ["OIDC_CLIENT_ID", data.OIDC_CLIENT_ID],
      ["OIDC_CLIENT_SECRET", data.OIDC_CLIENT_SECRET],
      ["OIDC_DISCOVERY_URL", data.OIDC_DISCOVERY_URL],
    ] as const;
    const setVars = oidcVars.filter(([, v]) => v);
    const missingVars = oidcVars.filter(([, v]) => !v);

    if (setVars.length > 0 && missingVars.length > 0) {
      for (const [name] of missingVars) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: [name],
          message: `${name} is required when OIDC SSO is partially configured. Set all three OIDC variables (OIDC_CLIENT_ID, OIDC_CLIENT_SECRET, OIDC_DISCOVERY_URL) or none.`,
        });
      }
    }

    // Stripe billing requires all vars or none. Partial config would otherwise
    // disable billing/webhooks silently, leaving checkout state stale.
    const stripeVars = [
      ["STRIPE_SECRET_KEY", data.STRIPE_SECRET_KEY],
      ["STRIPE_WEBHOOK_SECRET", data.STRIPE_WEBHOOK_SECRET],
      ["STRIPE_PRICE_SOLO_MONTHLY", data.STRIPE_PRICE_SOLO_MONTHLY],
      ["STRIPE_PRICE_SOLO_ANNUAL", data.STRIPE_PRICE_SOLO_ANNUAL],
      ["STRIPE_PRICE_TEAM_MONTHLY", data.STRIPE_PRICE_TEAM_MONTHLY],
      ["STRIPE_PRICE_TEAM_ANNUAL", data.STRIPE_PRICE_TEAM_ANNUAL],
      ["STRIPE_PRICE_SCALE_MONTHLY", data.STRIPE_PRICE_SCALE_MONTHLY],
      ["STRIPE_PRICE_SCALE_ANNUAL", data.STRIPE_PRICE_SCALE_ANNUAL],
    ] as const;
    const setStripeVars = stripeVars.filter(([, v]) => v);
    const missingStripeVars = stripeVars.filter(([, v]) => !v);

    if (setStripeVars.length > 0 && missingStripeVars.length > 0) {
      for (const [name] of missingStripeVars) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: [name],
          message: `${name} is required when Stripe billing is partially configured. Set all Stripe billing variables or none.`,
        });
      }
    }

  });

export const STRIPE_BILLING_ENV_KEYS = [
  "STRIPE_SECRET_KEY",
  "STRIPE_WEBHOOK_SECRET",
  "STRIPE_PRICE_SOLO_MONTHLY",
  "STRIPE_PRICE_SOLO_ANNUAL",
  "STRIPE_PRICE_TEAM_MONTHLY",
  "STRIPE_PRICE_TEAM_ANNUAL",
  "STRIPE_PRICE_SCALE_MONTHLY",
  "STRIPE_PRICE_SCALE_ANNUAL",
] as const;

type StripeBillingEnv = Partial<
  Record<(typeof STRIPE_BILLING_ENV_KEYS)[number], string | undefined>
>;

export function getMissingStripeBillingVars(config: StripeBillingEnv): string[] {
  const configuredCount = STRIPE_BILLING_ENV_KEYS.filter((key) =>
    Boolean(config[key]),
  ).length;

  if (configuredCount === 0 || configuredCount === STRIPE_BILLING_ENV_KEYS.length) {
    return [];
  }

  return STRIPE_BILLING_ENV_KEYS.filter((key) => !config[key]);
}

export function isStripeBillingConfigured(config: StripeBillingEnv): boolean {
  return STRIPE_BILLING_ENV_KEYS.every((key) => Boolean(config[key]));
}

/**
 * Validated environment variables. Uses lazy initialization so the schema
 * is only parsed on first access at runtime — not at import time. This
 * prevents build-time prerendering from failing when env vars aren't
 * available (e.g., Railway injects variables only at deploy time, not
 * during the build phase).
 */
export const env = new Proxy({} as z.infer<typeof envSchema>, {
  get(_, prop: string | symbol) {
    // During build-time prerendering, env vars aren't available.
    // Return safe defaults so the prerenderer can boot without crashing.
    if (import.meta.prerender) {
      return "";
    }

    if (typeof prop === "symbol") return undefined;

    // Parse once on first access, then cache for all subsequent reads
    if (!(globalThis as Record<string, unknown>).__env) {
      // Railway preview environments can inherit a DATABASE_URL whose service
      // reference has an empty hostname. Migration and seed commands already
      // recover from this using the individual PG/proxy variables; normalize
      // the runtime value the same way before validating the complete config.
      const result = envSchema.safeParse({
        ...process.env,
        DATABASE_URL: resolveDatabaseUrl(process.env),
      });
      if (!result.success) {
        const missing = result.error.issues
          .map((i) => `  - ${i.path.join(".")}: ${i.message}`)
          .join("\n");
        console.error(
          `\n[Reqcore] ❌ Missing or invalid environment variables:\n${missing}\n\n` +
            `Ensure these variables are set in your Railway service (Settings → Variables).\n` +
            `Required: DATABASE_URL, BETTER_AUTH_SECRET, S3_ENDPOINT, S3_ACCESS_KEY, S3_SECRET_KEY, S3_BUCKET\n` +
            `Required when not on Railway: BETTER_AUTH_URL (or generate a Railway domain)\n` +
            `Optional: BETTER_AUTH_TRUSTED_ORIGINS, S3_REGION (default: us-east-1), S3_FORCE_PATH_STYLE (default: true), TRUSTED_PROXY (default: cloudflare in production), TRUSTED_PROXY_IP, DEMO_ORG_SLUG, RESEND_API_KEY, RESEND_RECEIVING_API_KEY, RESEND_FROM_EMAIL, RESEND_CANDIDATE_FROM_EMAIL, RESEND_REPLY_DOMAIN, RESEND_WEBHOOK_SECRET, SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, SMTP_FROM, SMTP_SECURE, OIDC_CLIENT_ID, OIDC_CLIENT_SECRET, OIDC_DISCOVERY_URL, OIDC_PROVIDER_NAME, AUTH_GOOGLE_CLIENT_ID, AUTH_GOOGLE_CLIENT_SECRET, AUTH_GITHUB_CLIENT_ID, AUTH_GITHUB_CLIENT_SECRET, AUTH_MICROSOFT_CLIENT_ID, AUTH_MICROSOFT_CLIENT_SECRET, AUTH_MICROSOFT_TENANT_ID\n`,
        );
        throw result.error;
      }
      (globalThis as Record<string, unknown>).__env = result.data;
    }

    return (
      (globalThis as Record<string, unknown>).__env as Record<string, unknown>
    )[prop];
  },
});
